apiVersion: v1
kind: Service
metadata:
  labels:
    app: haproxy
  name: haproxy
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: haproxy
