apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy
  labels:
    app: haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
        - image: oudamchea/kubernetes:haproxy_new
          name: haproxy
          ports:
            - containerPort: 80
              name: haproxy
